/**
 * Sabian Symbols Engine
 * 360 symbolic images, one for each degree of the zodiac.
 * Each entry: [sign(0-11), degree(1-30), symbol, theme]
 */

const SABIAN_SYMBOLS = [
  // ARIES (sign 0)
  [0,1,"A woman has risen out of the ocean, a seal is embracing her","Emergence, spiritual origins"],
  [0,2,"A comedian entertaining a group","Joy, entertainment, lightness"],
  [0,3,"A cameo profile of a man in the outline of his country","Identity rooted in heritage"],
  [0,4,"Two lovers strolling through a secluded walk","Intimacy, private connection"],
  [0,5,"A triangle with wings","Aspiration, the trinity in motion"],
  [0,6,"A square brightly lighted on one side","Partial revelation, shadow and light"],
  [0,7,"A man successfully expressing himself in two realms","Dual mastery, bridge between worlds"],
  [0,8,"A woman's hat with streamers blown by the east wind","Openness to higher influence"],
  [0,9,"A crystal gazer","Inner vision, prophecy"],
  [0,10,"A teacher gives new symbolic forms to traditional images","Renewal of ancient wisdom"],
  [0,11,"The president of the country","Leadership, collective responsibility"],
  [0,12,"A flock of wild geese","Migration, collective instinct, freedom"],
  [0,13,"An unexploded bomb reveals an unsuccessful social protest","Suppressed tension, unreleased potential"],
  [0,14,"A serpent coiling near a man and a woman","Temptation, primal energy, choice"],
  [0,15,"An Indian weaving a blanket","Patient creation, ancestral craft"],
  [0,16,"Brownies dancing in the setting sun","Elemental joy, twilight magic"],
  [0,17,"Two prim spinsters sitting together in silence","Conservative tradition, unspoken bonds"],
  [0,18,"An empty hammock stretched between two trees","Rest, suspension, potential reactivation"],
  [0,19,"The 'magic carpet' of Oriental imagery","Fantasy, wish-fulfillment, transcendence"],
  [0,20,"A young girl feeding birds in winter","Nurturing life through barren times"],
  [0,21,"A pugilist entering the ring","Combat readiness, facing challenges"],
  [0,22,"The gate to the garden of desire","Threshold of fulfillment"],
  [0,23,"A woman in pastel colors carrying a heavy and valuable but veiled load","Bearing gifts quietly"],
  [0,24,"An open window and a net curtain blowing into a cornucopia","Abundance flowing in"],
  [0,25,"The possibility of having one's wishes fulfilled","Manifestation, wishing well"],
  [0,26,"A man possessed of more gifts than he can express","Overflow of talent"],
  [0,27,"Through imagination a lost opportunity is regained","Second chances, creative recovery"],
  [0,28,"A large disappointed audience","Unmet expectations, collective letdown"],
  [0,29,"A celestial choir singing","Harmony, divine inspiration"],
  [0,30,"A duck pond and its brood","Domesticity, protected nurturing"],
  // TAURUS (sign 1)
  [1,1,"A clear mountain stream","Purity, natural flow"],
  [1,2,"An electrical storm","Sudden energy release, breakthrough"],
  [1,3,"Steps up to a lawn blooming with clover","Gradual ascent to abundance"],
  [1,4,"The rainbow's pot of gold","Promise, reward after effort"],
  [1,5,"A widow at an open grave","Transformation through loss"],
  [1,6,"A bridge being built across a gorge","Connection between opposites"],
  [1,7,"A woman of Samaria comes to draw water","Sacred service, meeting the divine"],
  [1,8,"A sleigh without snow","Preparation without conditions met"],
  [1,9,"A christmas tree decorated","Celebration, collective joy"],
  [1,10,"A red cross nurse","Healing service, compassion in crisis"],
  [1,11,"A woman watering flowers in her garden","Devoted cultivation"],
  [1,12,"Window shoppers","Desire without possession"],
  [1,13,"A man handling baggage","Managing life's burdens"],
  [1,14,"Shellfish groping and children playing","Early stages of consciousness"],
  [1,15,"A man muffled up, with a rakish silk hat","Hidden identity, social presentation"],
  [1,16,"An old man attempting vainly to reveal the Mysteries","Esoteric knowledge, failed transmission"],
  [1,17,"A symbolical battle between 'swords' and 'torches'","Conflict between intellect and inspiration"],
  [1,18,"A woman holding a bag out of a window","Offering, releasing to the world"],
  [1,19,"A newly formed continent","Emergence of new possibility"],
  [1,20,"Wisps of winglike clouds streaming across the sky","Transition, spiritual movement"],
  [1,21,"A finger pointing to a line in an open book","Guidance, specific direction"],
  [1,22,"White doves in a sunlit field","Peace, blessing, innocence"],
  [1,23,"A jewelry shop filled with magnificent gems","Accumulated value, beauty"],
  [1,24,"An indian warrior riding fiercely, human scalps hanging at his belt","Fierce achievement, martial prowess"],
  [1,25,"A vast public park","Shared beauty, communal space"],
  [1,26,"A Spaniard serenading his beloved","Romantic devotion, cultural expression"],
  [1,27,"A squaw selling beads","Traditional craft, economic survival"],
  [1,28,"A woman pursued by mature romance","Soul longing, deep relationship"],
  [1,29,"Two cobblers working at a table","Cooperative craftsmanship"],
  [1,30,"A peacock parading on an ancient lawn","Display, pride, aristocratic beauty"],
  // GEMINI (sign 2)
  [2,1,"A glass-bottomed boat in still water","Transparency, seeing beneath surface"],
  [2,2,"Santa Claus filling stockings furtively","Generous giving in secret"],
  [2,3,"The garden of the Tuileries in Paris","Cultivated beauty, historical grandeur"],
  [2,4,"Holly and mistletoe reawaken old memories","Seasonal ritual, ancestral memory"],
  [2,5,"A radical magazine asking for action","Revolutionary ideas, call to change"],
  [2,6,"Drilling for oil","Penetrating to life's essence"],
  [2,7,"An old-fashioned well","Ancient sustenance, reliable resources"],
  [2,8,"Aroused strikers surround a factory","Collective assertion of rights"],
  [2,9,"A quiver filled with arrows","Readiness, stored potential"],
  [2,10,"An airplane falling","Sudden descent, hubris corrected"],
  [2,11,"Newly opened lands offer the pioneer new opportunities","Frontier spirit, fresh beginnings"],
  [2,12,"A black girl fights for her independence","Claiming autonomy, breaking barriers"],
  [2,13,"A great musician at his piano","Mastery in service of beauty"],
  [2,14,"Two people living far apart in telepathic communication","Soul connection across distance"],
  [2,15,"Two Dutch children talking","Simple exchange, cultural innocence"],
  [2,16,"A woman agitator making a speech","Passionate advocacy"],
  [2,17,"The head of a robust youth changes into that of a mature thinker","Growth of wisdom"],
  [2,18,"Two Chinese men talking Chinese in a Western crowd","Cultural roots amid foreign contexts"],
  [2,19,"A large archaic volume reveals a hidden knowledge","Ancient wisdom rediscovered"],
  [2,20,"A modern cafeteria displays an abundance of food","Plenty, social nourishment"],
  [2,21,"A labor demonstration","Collective power, solidarity"],
  [2,22,"A barn dance","Community celebration, simple joy"],
  [2,23,"Three fledglings in a nest high in a tree","Vulnerability and protection"],
  [2,24,"Children skating over a frozen pond","Skill on thin ice, playful risk"],
  [2,25,"A man trimming palms","Refinement, maintenance of growth"],
  [2,26,"Winter frost in the woods","Hidden life, beautiful stasis"],
  [2,27,"A gypsy emerging from the forest","Emergence from the wild, liminal figure"],
  [2,28,"Bankruptcy granted to him","Release from debt, fresh start"],
  [2,29,"The first mocking bird of spring","New voice, heralding change"],
  [2,30,"A parade of bathing beauties before large beach crowds","Display, public enjoyment"],
  // CANCER (sign 3)
  [3,1,"A furled and an unfurled flag displayed from a vessel","Readiness and repose"],
  [3,2,"A man on a magic carpet hovering over a large area of land","Elevated perspective, magical overview"],
  [3,3,"An arctic explorer leads a reindeer through icy canyons","Pioneering through cold terrain"],
  [3,4,"A cat arguing with a mouse","Instinct versus cunning, predator and prey"],
  [3,5,"At a railroad crossing, an automobile is wrecked by a train","Collision of old and new forces"],
  [3,6,"Game birds feathering their nests","Instinctive preparation, domestic readiness"],
  [3,7,"Two fairies on a moonlit night","Enchantment, ethereal beauty"],
  [3,8,"Rabbits dressed in clothes and on parade","Social performance, charming conformity"],
  [3,9,"A tiny nude miss reaches in the water for a fish","Innocent desire, reaching for sustenance"],
  [3,10,"A large diamond in the first stages of the cutting process","Potential being refined"],
  [3,11,"A clown making grimaces","Comic mask, emotional release through humor"],
  [3,12,"A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher","Ancient souls, maternal transmission"],
  [3,13,"One hand slightly flexed with a very prominent thumb","Will directed, practical determination"],
  [3,14,"A very old man facing a vast dark space to the northeast","Confronting the unknown at life's end"],
  [3,15,"A group of people who have overeaten and enjoyed it","Satiation, communal indulgence"],
  [3,16,"A man studying a mandala in front of him with the help of a very ancient book","Sacred geometry, ancient guidance"],
  [3,17,"The unfoldment of multilevel potentialities issuing from an original germ","Evolutionary unfolding"],
  [3,18,"A hen scratching for her chicks","Maternal industry, sustaining the young"],
  [3,19,"A priest performing a marriage ceremony","Sacred union, ritual blessing"],
  [3,20,"Gondoliers in a serenade","Romantic tradition, aesthetic pleasure"],
  [3,21,"A prima donna singing","Expressive peak, public gift"],
  [3,22,"A woman awaiting a sailboat","Patient expectation, longing"],
  [3,23,"Meeting of a literary society","Intellectual community, shared love of words"],
  [3,24,"A woman and two men on a bit of sunlit land facing south","Basking in light, alignment with warmth"],
  [3,25,"A will-o-the-wisp","Illusion, elusive guidance"],
  [3,26,"Guests are reading in the library of a luxurious home","Leisure of the cultivated mind"],
  [3,27,"A violent storm in a canyon filled with expensive homes","Wealth exposed to elemental force"],
  [3,28,"A modern Pocahontas","Indigenous wisdom meets new world"],
  [3,29,"A Muse weighing twins","Inspiration calibrated, dual possibilities assessed"],
  [3,30,"A Daughter of the American Revolution","Heritage pride, ancestral identity"],
  // LEO (sign 4)
  [4,1,"Blood rushes to a man's head as his vital energies are mobilized","Vitality rising"],
  [4,2,"An epidemic of mumps","Collective vulnerability, contagious conditions"],
  [4,3,"A middle-aged woman, her long hair newly bobbed","Transition, new self-presentation"],
  [4,4,"A man formally dressed and a deer with its horns folded","Poise meeting wildness"],
  [4,5,"Rock formations tower over a deep canyon","Geological time, endurance"],
  [4,6,"A conservative, old-fashioned lady is confronted by a 'hippie' girl","Generation clash, value confrontation"],
  [4,7,"The constellations of stars in the sky","Cosmic pattern, stellar guidance"],
  [4,8,"A Bolshevik propagandist","Radical ideas, ideological passion"],
  [4,9,"Glass blowers shape beautiful vases with their controlled breathing","Breath as creative force"],
  [4,10,"Early morning dew","Freshness, renewal"],
  [4,11,"Children play on a swing hanging from the branches of a huge oak","Joy grounded in strength"],
  [4,12,"An evening lawn party of adults","Refined sociability, outdoor pleasure"],
  [4,13,"An old sea captain rocking himself on the porch of his cottage","Memory of adventure, earned rest"],
  [4,14,"The human soul, in its eagerness for new experiences, seeks embodiment","Incarnation, desire for form"],
  [4,15,"A pageant moving along a street packed with people","Collective celebration"],
  [4,16,"The storm ended, all nature rejoices in brilliant sunshine","Renewal after crisis"],
  [4,17,"A volunteer church choir makes social event of rehearsal","Community effort, joyful practice"],
  [4,18,"A teacher of chemistry","Analytical mastery, transformation of matter"],
  [4,19,"A houseboat party","Celebration on fluid ground"],
  [4,20,"The zeal of a man fighting for an ideal","Passionate conviction"],
  [4,21,"Chickens intoxicated","Innocence disturbed, lost bearing"],
  [4,22,"A carrier pigeon fulfilling its mission","Faithful delivery, reliable messenger"],
  [4,23,"A bareback rider in a circus displays her dangerous skills","Daring display, trust without protection"],
  [4,24,"Many little birds on the limb of a large tree","Community resting on strength"],
  [4,25,"A large camel crossing a vast and forbidding desert","Endurance through adversity"],
  [4,26,"After the heavy storm, a rainbow","Promise after suffering"],
  [4,27,"Daybreak - the luminescence of dawn in the eastern sky","New beginning, light emerging"],
  [4,28,"Many little birds on the limb of a large tree singing merrily","Joyful community, harmony"],
  [4,29,"A mermaid emerges from the ocean ready for rebirth in human form","Crossing from one realm to another"],
  [4,30,"An unsealed letter has vital and confidential information","Open secrets, vulnerable communication"],
  // VIRGO (sign 5)
  [5,1,"In a portrait the best of a man's features and traits are idealized","Aspiration through image"],
  [5,2,"A large white cross dominates the landscape","Faith as anchor, moral landmark"],
  [5,3,"Two angels bringing protection","Divine guardianship"],
  [5,4,"A colored child playing with white children","Innocence transcending difference"],
  [5,5,"A man becoming aware of nature spirits and normally unseen spiritual agencies","Expanded perception"],
  [5,6,"A merry-go-round","Cycles, return, playful spinning"],
  [5,7,"A harem","Sequestered beauty, controlled eros"],
  [5,8,"A five-year-old child takes a first dancing lesson","Early steps in embodied grace"],
  [5,9,"An expressionist painter at her easel","Emotional intensity rendered visible"],
  [5,10,"Two heads looking out and beyond the shadows","Vision beyond limitation"],
  [5,11,"A boy molded in his mother's aspirations for him","Shaped by love's expectation"],
  [5,12,"A bride with her veil snatched away","Revelation of the hidden self"],
  [5,13,"A powerful statesman overcomes a state of political hysteria","Leadership steadying collective fear"],
  [5,14,"A family tree","Roots, continuity, inherited patterns"],
  [5,15,"A fine lace ornamental handkerchief","Delicate refinement"],
  [5,16,"An orangutan","Primal instinct, evolutionary root"],
  [5,17,"A volcanic eruption","Pent-up force released, transformation"],
  [5,18,"Two university graduates are shaking hands","Achievement recognized, peer acknowledgment"],
  [5,19,"A swimming race","Competitive drive, fluid contest"],
  [5,20,"A caravan of cars headed to the west coast","Collective migration, seeking"],
  [5,21,"A girls' basketball team","Cooperative athletics, team spirit"],
  [5,22,"A royal coat of arms","Inherited authority, noble heritage"],
  [5,23,"A lion tamer rushes fearlessly into the arena","Mastery of instinct, courage"],
  [5,24,"Mary and her white lamb","Innocence and its faithful companion"],
  [5,25,"A flag at half-mast in front of a large building","Public mourning, honor"],
  [5,26,"A boy with a censer serves the priest near the altar","Sacred service, initiatory role"],
  [5,27,"Grande dames at a formal party","Aristocratic tradition, ceremony"],
  [5,28,"A bald-headed man who has seized power","Ambition stripped of pretense"],
  [5,29,"A seeker after occult knowledge is reading an ancient scroll","Hidden knowledge sought"],
  [5,30,"A false call unheard in attention to immediate service","Discernment, immunity to distraction"],
  // LIBRA (sign 6)
  [6,1,"A butterfly made perfect by a dart through it","Beauty pinned, fleeting made permanent"],
  [6,2,"The light of the sixth race transmuted to the seventh","Evolutionary transmutation"],
  [6,3,"The dawn of a new day reveals everything changed","Radical transformation overnight"],
  [6,4,"A group of young people sit in spiritual communion around a campfire","Sacred circle, collective attunement"],
  [6,5,"A man teaching the true inner knowledge","Esoteric transmission"],
  [6,6,"The ideals of a man abundantly crystallized","Ideals made manifest"],
  [6,7,"A woman feeding chickens and protecting them from the hawk","Nurturing under threat"],
  [6,8,"A blazing fireplace in a deserted home","Warmth without witness, hearth of memory"],
  [6,9,"Three old masters hanging in a special room in an art gallery","Reverence for mastery"],
  [6,10,"A canoe approaching safety through dangerous waters","Navigation through crisis"],
  [6,11,"A professor peering over his glasses at his students","Critical discernment, intellectual authority"],
  [6,12,"Miners are surfacing from a deep coal mine","Emergence from underworld labor"],
  [6,13,"Children playing around five mounds of sand","Archetypal forms in play"],
  [6,14,"A noon siesta","Rest at peak of day, renewal"],
  [6,15,"Circular paths","Cycles, eternal return"],
  [6,16,"A boat landing washed away","Temporary structures, impermanence"],
  [6,17,"A retired sea captain watches ships entering and leaving the harbor","Wisdom observing ongoing voyage"],
  [6,18,"Two men placed under arrest","Accountability, social order enforced"],
  [6,19,"A gang of robbers in hiding","Shadow organized, collective transgression"],
  [6,20,"A rabbi performing his duties","Sacred tradition, communal service"],
  [6,21,"A Sunday crowd enjoying the city park","Democratic leisure, shared beauty"],
  [6,22,"A child giving birds a drink at a fountain","Tending the innocent, gentle nourishment"],
  [6,23,"Chanticleer's voice heralds the rising sun","Prophetic announcement, dawn called forth"],
  [6,24,"A butterfly spreading and losing its many-colored wings","Beauty released, transformation beyond form"],
  [6,25,"The sight of an autumn leaf brings to a pilgrim the sudden revelation of the harmony of the universe","Enlightenment through the ordinary"],
  [6,26,"An eagle and a large white dove turning into each other","Power and peace interchangeable"],
  [6,27,"An airplane hovering overhead","Elevated perspective, surveillance"],
  [6,28,"A man in the midst of brightening influences","Illumination gathering around one"],
  [6,29,"Humanity seeking to span the bridge of the rainbow","Aspiration toward divine connection"],
  [6,30,"Three mounds of knowledge on a philosopher's head","Accumulated wisdom"],
  // SCORPIO (sign 7)
  [7,1,"A sight-seeing bus filled with tourists","Observation, collective wonder"],
  [7,2,"A broken bottle and spilled perfume","Fragrance of the past, loss releasing essence"],
  [7,3,"A house-raising party in a small village","Community building, cooperative labor"],
  [7,4,"A youth carries a lighted candle in a darkened room","Bearing light into shadow"],
  [7,5,"A massive rocky shore resists the pounding of the sea","Steadfastness against pressure"],
  [7,6,"The gold rush tears men away from their native soil","Collective fever, displacement by desire"],
  [7,7,"Deep sea divers","Exploring hidden depths"],
  [7,8,"A calm lake bathed in moonlight","Reflective peace, lunar serenity"],
  [7,9,"Dental work on a child","Invasive care, future health ensured"],
  [7,10,"A fellowship supper reunites old comrades","Brotherhood, shared memory"],
  [7,11,"A drowning man is being rescued","Crisis and salvation, intervention"],
  [7,12,"An official embassy ball","Formal diplomacy, cultural ritual"],
  [7,13,"An inventor experiments with a new invention in his workshop","Creative tinkering, innovation"],
  [7,14,"Telephone linemen at work installing new connections","Creating networks, new communication"],
  [7,15,"Children playing around five mounds of sand","Innocent creation"],
  [7,16,"A girl's face breaking into a smile","Warmth emerging, joy revealed"],
  [7,17,"A woman the father of her own child","Self-sufficiency, inner masculine integrated"],
  [7,18,"A woods rich in autumn coloring","Abundance at season's turn, beauty in transition"],
  [7,19,"A parrot listening and talking to a man","Mimicry, intelligence through imitation"],
  [7,20,"A woman drawing two dark curtains aside","Revelation of hidden truths"],
  [7,21,"Obeying his conscience, a soldier resists orders","Moral courage, individual integrity"],
  [7,22,"Hunters starting out for duck","Purposeful pursuit, coordinated effort"],
  [7,23,"A rabbit metamorphoses into a nature spirit","Transformation into elemental form"],
  [7,24,"Crowds coming down the mountain to listen to one inspired man","Charisma, descent to teach"],
  [7,25,"An x-ray photograph","Seeing through surfaces"],
  [7,26,"Indians making camp in new territory","Adaptation, claiming new ground"],
  [7,27,"A military band on the march","Disciplined display, collective will"],
  [7,28,"The king of the fairies approaching his domain","Archetype assuming its realm"],
  [7,29,"An Indian squaw pleading to the chief for the lives of her children","Maternal courage, intercession"],
  [7,30,"Children in halloween costumes indulge in various pranks","Playful transgression"],
  // SAGITTARIUS (sign 8)
  [8,1,"Retired army veterans gather to reawaken old memories","Honor, collective reminiscence"],
  [8,2,"The ocean covered with whitecaps","Excitement across vast surface, energized expanse"],
  [8,3,"Two men playing chess","Strategic mind, patient contest"],
  [8,4,"A little child learning to walk with the encouragement of his parents","First steps, loving support"],
  [8,5,"An old owl up in a tree","Wisdom, watchful patience"],
  [8,6,"A game of cricket","Civilized contest, refined sportsmanship"],
  [8,7,"Cupid knocking at the door","Love requesting entry"],
  [8,8,"Within the depths of the earth new elements are being formed","Hidden gestation, deep creation"],
  [8,9,"A mother with her children on stairs","Ascending together, guided progress"],
  [8,10,"A golden-haired goddess of opportunity","Fortune beckoning"],
  [8,11,"The lamp of physical enlightenment at the left temple","Illumination, rational mind lit"],
  [8,12,"A flag turns into an eagle; the eagle into a chanticleer","Symbol evolving, transformation ascending"],
  [8,13,"A widow's past brought to light","Hidden history surfacing"],
  [8,14,"The pyramids and the sphinx","Ancient mystery, enduring monument"],
  [8,15,"The ground hog looking for its shadow on ground-hog day","Instinct, weather-sense"],
  [8,16,"Sea gulls watching a ship","Opportunism, freedom riding the wind"],
  [8,17,"An Easter sunrise service draws a joyous crowd","Collective renewal, resurrection"],
  [8,18,"Tiny children in sunbonnets","Protected innocence"],
  [8,19,"Pelicans moving their habitat","Group adaptation, communal migration"],
  [8,20,"In an open field a man is sowing grain","Planting for the future"],
  [8,21,"A child and a dog wearing borrowed eyeglasses","Playful mimicry, seeking vision"],
  [8,22,"A Chinese laundry","Diligent service, cultural persistence"],
  [8,23,"Immigrants entering a new country","Threshold crossing, new life begun"],
  [8,24,"A bluebird standing at the door of the house","Happiness close at hand"],
  [8,25,"A chubby boy on a hobbyhorse","Innocent ambition, play-mastery"],
  [8,26,"A flag-bearer in a battle","Bearing symbols under fire"],
  [8,27,"A sculptor at his work","Patient vision made material"],
  [8,28,"An old bridge over a beautiful stream still in perfect use","Tradition serving present needs"],
  [8,29,"A fat boy mowing the lawn","Wholesome labor, earthly duty"],
  [8,30,"The pope blessing the faithful","Authoritative benediction"],
  // CAPRICORN (sign 9)
  [9,1,"An indian chief claims power from the assembled tribe","Sovereign authority claimed"],
  [9,2,"Three stained-glass windows in a gothic church, one damaged by war","Sacred beauty marked by history"],
  [9,3,"The human soul receptive to growth and understanding","Open soul, capacity for growth"],
  [9,4,"A group of people outfitting a large canoe at the start of a journey","Collective preparation, embarkation"],
  [9,5,"Indians rowing a canoe and dancing a war dance","Ritualized aggression, tribal power"],
  [9,6,"Ten logs lie under an archway leading to darker woods","Threshold to mystery, gathered resources"],
  [9,7,"A veiled prophet of power","Hidden authority, masked influence"],
  [9,8,"In a sunlit home domesticated birds sing joyously","Tamed beauty, contentment"],
  [9,9,"An angel carrying a harp","Divine music, celestial messenger"],
  [9,10,"An albatross feeding from the hand of a sailor","Taming the wild, trust across species"],
  [9,11,"A large group of pheasant on a private estate","Abundance on hallowed ground"],
  [9,12,"An illustrated lecture on natural science reveals little-known aspects of life","Education expanding horizons"],
  [9,13,"A fire worshipper meditates on the ultimate realities of existence","Sacred contemplation"],
  [9,14,"An ancient bas-relief carved in granite remains a witness to a long-forgotten culture","Memory in stone"],
  [9,15,"Many toys in the children's ward of a hospital","Healing through play"],
  [9,16,"Boys and girls in gymnasium suits","Physical education, disciplined body"],
  [9,17,"A young girl surreptitiously bathing in the nude","Natural innocence, forbidden pleasure"],
  [9,18,"The Union Jack flag flies from a British warship","Imperial power, national symbol"],
  [9,19,"A child of about five with a huge shopping bag","Innocent ambition, large task in small hands"],
  [9,20,"A hidden choir singing during a religious service","Unseen support, invisible harmony"],
  [9,21,"A relay race","Passing on, cooperative succession"],
  [9,22,"A general accepting defeat gracefully","Dignity in loss, nobility of character"],
  [9,23,"Two awards for bravery in war","Recognition of courage"],
  [9,24,"A woman entering a convent","Renunciation, devoted service"],
  [9,25,"An oriental rug dealer in a store filled with precious ornaments","Accumulated cultural wealth"],
  [9,26,"A nature spirit dancing in the iridescent mist of a waterfall","Elemental grace, ephemeral beauty"],
  [9,27,"A mountain pilgrimage","Spiritual ascent, seeking the high place"],
  [9,28,"A large aviary","Collected voices, contained freedom"],
  [9,29,"A woman reading tea leaves","Divination, pattern reading"],
  [9,30,"A secret business conference","Strategic planning behind closed doors"],
  // AQUARIUS (sign 10)
  [10,1,"An old adobe mission","Enduring faith, humble service"],
  [10,2,"An unexpected thunderstorm","Sudden disruption, elemental surprise"],
  [10,3,"A deserter from the navy","Breaking ranks, freedom claimed"],
  [10,4,"A Hindu healer glows with a mystic nimbus","Sacred radiance, healing presence"],
  [10,5,"A council of ancestors has been called to guide a young chief","Ancestral wisdom in leadership"],
  [10,6,"A performer of a mystery play","Living the archetype, sacred drama"],
  [10,7,"A child born of an eggshell","Unusual origin, emergence from symbol"],
  [10,8,"Beautifully gowned wax figures on display","Perfection preserved, idealized form"],
  [10,9,"A flag is seen turning into an eagle","Symbol animated, spirit embodied"],
  [10,10,"A popularity that proves to be a fleeting thing","Ephemeral fame"],
  [10,11,"During a silent hour, a man receives a new inspiration which may change his life","Receptivity to divine prompting"],
  [10,12,"On the altar of the Mayan temple a young couple makes their vows","Sacred union in ancient ritual"],
  [10,13,"A barometer","Reading atmospheric pressure, advance warning"],
  [10,14,"A train entering a tunnel","Passage through darkness toward light"],
  [10,15,"Two lovebirds sitting on a fence and singing happily","Simple joy, harmony in pairs"],
  [10,16,"A big-businessman at his desk","Command of material world"],
  [10,17,"A watchmaker at his trade","Precision, mastery of time"],
  [10,18,"A man unmasked","True face revealed"],
  [10,19,"A forest fire quenched","Collective effort containing chaos"],
  [10,20,"A large white dove bearing a message","Peace, divine communication"],
  [10,21,"A woman disappointed and disillusioned, courageously facing a seemingly empty life","Endurance through disillusion"],
  [10,22,"A rug placed on a floor for children to play on","Prepared ground for development"],
  [10,23,"A big bear sitting down and waving all its paws","Unexpected gentleness from power"],
  [10,24,"A man turning his back on his passions and teaching from his experience","Wisdom earned through renunciation"],
  [10,25,"A butterfly with a third wing on its left side","Unexpected mutation, gift of extra capacity"],
  [10,26,"A garage man testing a car's battery with a hydrometer","Technical diagnosis, readiness check"],
  [10,27,"An ancient pottery bowl filled with violets","Old vessel holding delicate beauty"],
  [10,28,"A tree felled and sawed to ensure a supply of wood for the winter","Practical provision, foresight"],
  [10,29,"Butterfly emerging from a chrysalis","Transformation complete, new form"],
  [10,30,"Moonlit fields, once babylon, are blooming white","Ancient ruins transformed to beauty"],
  // PISCES (sign 11)
  [11,1,"In a meeting of a scientific society, the clerk is taking notes","Recording for posterity"],
  [11,2,"A squirrel hiding from hunters","Instinctive self-protection"],
  [11,3,"A petrified forest","Ancient life preserved, timeless past"],
  [11,4,"Heavy traffic on a narrow isthmus","Congestion at the bridge point"],
  [11,5,"A church bazaar","Community fundraising, social bonding"],
  [11,6,"Officers on dress parade","Disciplined display, institutional pride"],
  [11,7,"A cross lying on rocks and a skull beneath it","Mortality and faith side by side"],
  [11,8,"A girl blowing a bugle","Clear announcement, awakening call"],
  [11,9,"The race begins: intent on outdistancing his rivals, a jockey spurs his horse to great speed","Competitive drive, focused intensity"],
  [11,10,"An aviator in the clouds","Vision above earthly confusion"],
  [11,11,"Men traveling a narrow path, seeking illumination","Pilgrimage, seeking the light"],
  [11,12,"In the sanctuary of an occult brotherhood, newly initiated members are being examined and tested","Initiation, proving oneself"],
  [11,13,"A sword, used in many battles, is now in a museum","Retired power, historical artifact"],
  [11,14,"A lady wrapped in fox fur","Sophisticated warmth, animal instinct refined"],
  [11,15,"An officer drilling his men in a simulated attack","Preparation, rehearsed readiness"],
  [11,16,"In the quiet of his study a creative individual experiences a flow of inspiration","Solitary inspiration"],
  [11,17,"An Easter promenade","Celebratory renewal, public joy"],
  [11,18,"In a gigantic tent, villagers witness a spectacular performance","Collective wonder, theatrical spectacle"],
  [11,19,"A master instructing his disciples","Teaching through presence"],
  [11,20,"A table set for an evening meal","Anticipation of nourishment"],
  [11,21,"Under the watchful and kind eyes of a Chinese servant, a girl fondles a little white lamb","Gentle care across cultures"],
  [11,22,"A man bringing down the new law from Sinai","Divine legislation, revealed order"],
  [11,23,"Spiritist phenomena are producing a glow of light in the darkened room","Contact with the beyond"],
  [11,24,"An inhabited island","Community in isolation, self-sufficient world"],
  [11,25,"The purging of the priesthood","Institutional renewal, reform"],
  [11,26,"A new moon reveals that it's time for people to go ahead with their different projects","New beginning, fresh initiative"],
  [11,27,"The harvest moon illuminates a clear autumnal sky","Fulfillment, reaping"],
  [11,28,"A fertile garden under the full moon","Lunar abundance, night cultivation"],
  [11,29,"Light breaking into many colors as it passes through a prism","Spectrum revealed, unity into diversity"],
  [11,30,"A majestic rock formation resembling a face is idealized by a boy who takes it as his ideal of greatness — a man finally resembles it","Becoming what you admire"],
]

function getSabianSymbol(lon) {
  const signIdx = Math.floor(lon / 30)
  const raw = lon % 30
  const degInSign = raw === 0 ? 30 : Math.ceil(raw) // Sabian uses 1-30, ceiling

  // Find exact match first
  const exact = SABIAN_SYMBOLS.find(s => s[0] === signIdx && s[1] === degInSign)
  if (exact) return { sign: signIdx, degree: degInSign, symbol: exact[2], theme: exact[3] }

  // Find closest in same sign
  const sameSign = SABIAN_SYMBOLS.filter(s => s[0] === signIdx)
  if (sameSign.length > 0) {
    const closest = sameSign.reduce((prev, curr) =>
      Math.abs(curr[1] - degInSign) < Math.abs(prev[1] - degInSign) ? curr : prev
    )
    return { sign: signIdx, degree: degInSign, symbol: closest[2], theme: closest[3], approximate: true }
  }

  return { sign: signIdx, degree: degInSign, symbol: 'Symbol not yet catalogued', theme: 'Mystery' }
}

const SIGN_NAMES = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces']

export function getSabianProfile(natalChart) {
  const result = {}
  const PLANETS = ['sun','moon','mercury','venus','mars','jupiter','saturn','uranus','neptune','pluto','northNode']

  for (const planet of PLANETS) {
    const p = natalChart.planets[planet]
    if (!p) continue
    const sabian = getSabianSymbol(p.lon)
    result[planet] = {
      lon: p.lon,
      sign: p.sign,
      degree: Math.ceil(p.degree),
      sabian: sabian.symbol,
      theme: sabian.theme,
      approximate: sabian.approximate || false,
    }
  }

  // Also for angles
  for (const angle of ['asc','mc']) {
    const a = natalChart.angles[angle]
    if (!a) continue
    const sabian = getSabianSymbol(a.lon)
    result[angle] = {
      lon: a.lon,
      sign: a.sign,
      degree: Math.ceil(a.degree),
      sabian: sabian.symbol,
      theme: sabian.theme,
      approximate: sabian.approximate || false,
    }
  }

  return result
}

export { SIGN_NAMES }
