import { useState } from 'react'
import { useAboveInsideStore } from '../../store/useAboveInsideStore'

function formatDuration(startTime, endTime) {
  const ms = (endTime || Date.now()) - startTime
  const mins = Math.floor(ms / 60000)
  if (mins < 60) return `${mins} min`
  const hrs = Math.floor(mins / 60)
  const rem = mins % 60
  return `${hrs}h ${rem}m`
}

function formatDate(timestamp) {
  return new Date(timestamp).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })
}

export default function SessionSummary({ session, clientProfile = {}, practitionerName = 'Your Practitioner' }) {
  const { endSession: _endSession } = useAboveInsideStore()
  const [copied, setCopied] = useState(false)
  const [showScheduler, setShowScheduler] = useState(false)

  const s = session || {
    clientId: 'demo',
    startTime: Date.now() - 65 * 60 * 1000,
    endTime: Date.now(),
    notes: '',
    actionItems: [
      'Daily 5-minute sacral check-in practice',
      'Journaling prompt: "Where am I waiting for permission that is already mine to give?"',
      'One honest conversation this week',
    ],
    frameworks: ['Human Design', 'Gene Keys', 'Astrology'],
    analysis: {
      insights: [
        'Sacral authority is being bypassed through mental override',
        'The 3/5 profile karma is completing — trial and error phase resolving into wisdom',
        'Solar plexus wave patterns connected to family of origin dynamics',
      ],
      followUpQuestions: [
        'What would it feel like to make one decision purely from gut response?',
        'Where in your life are you still in the trial phase of your 3rd line?',
        'How does your emotional wave relate to the retreat pattern in your family?',
      ],
      patterns: 'Three sessions showing the mental override of sacral authority. The emotional wave timing is clarifying: 3–5 day cycles with breakthrough insights at the bottom of the wave.',
    },
  }

  const completedCount = s.actionItems?.filter((_, i) => s.checkedItems?.[i]).length || 0

  const summaryText = `# Session Summary — ${formatDate(s.startTime)}

**Client:** ${clientProfile.name || 'Client'} · ${clientProfile.hdType || 'HD Type'} · Life Path ${clientProfile.lifePath || '?'}
**Duration:** ${formatDuration(s.startTime, s.endTime)}
**Frameworks Explored:** ${s.frameworks?.join(', ') || 'Human Design, Astrology'}

## Session Overview

${s.analysis?.insights ? 
  `This session brought significant clarity around your ${clientProfile.hdType || 'Human Design'} authority and how you're navigating decisions in your life. We explored the patterns that keep emerging around self-trust and what it means to honor your unique design.

The conversation moved into deep territory around your profile and the karma currently completing in your life. There's a palpable readiness for the next phase of your journey — less figuring out, more trusting and receiving.

Key themes that wove through our time together: authority, emotional intelligence, and the courage it takes to live from your truth rather than from conditioning.` 
  : s.notes || 'Session notes not available.'}

## Key Insights
${s.analysis?.insights?.map(i => `- ${i}`).join('\n') || '- See practitioner notes'}

## Your Action Items
${s.actionItems?.map(item => `☐ ${item}`).join('\n') || '☐ Reflect on our session themes'}

## Questions to Explore Next Time
${s.analysis?.followUpQuestions?.map((q, i) => `${i + 1}. ${q}`).join('\n') || '1. What has shifted since our last session?'}

## Patterns Emerging
${s.analysis?.patterns || 'Patterns will emerge across multiple sessions.'}

---
*Summary generated by AETHER · ${practitionerName}*`

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  return (
    <div style={{
      background: 'var(--panel-bg, rgba(15,12,30,0.9))',
      border: '1px solid var(--glass-border, rgba(201,168,76,0.2))',
      borderRadius: 16,
      padding: 24,
      backdropFilter: 'blur(20px)',
    }}>
      {/* Header */}
      <div style={{ marginBottom: 20, borderBottom: '1px solid var(--glass-border, rgba(201,168,76,0.15))', paddingBottom: 16 }}>
        <h2 style={{
          fontFamily: 'Cinzel, serif',
          fontSize: '1.1rem',
          letterSpacing: '0.1em',
          color: 'var(--gold, #c9a84c)',
          margin: '0 0 6px',
        }}>
          📄 Session Summary
        </h2>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.9rem', opacity: 0.75 }}>
            📅 {formatDate(s.startTime)}
          </span>
          <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.9rem', opacity: 0.75 }}>
            ⏱ {formatDuration(s.startTime, s.endTime)}
          </span>
          {s.frameworks?.length > 0 && (
            <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.9rem', opacity: 0.75 }}>
              🔭 {s.frameworks.join(' · ')}
            </span>
          )}
        </div>
      </div>

      {/* Client info */}
      {clientProfile.name && (
        <div style={{
          background: 'rgba(201,168,76,0.06)',
          borderRadius: 10,
          padding: '10px 14px',
          marginBottom: 18,
          display: 'flex',
          gap: 16,
          flexWrap: 'wrap',
        }}>
          <span style={{ fontFamily: 'Cinzel, serif', fontSize: '0.85rem', color: 'var(--gold, #c9a84c)' }}>
            {clientProfile.name}
          </span>
          {clientProfile.hdType && (
            <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.9rem', opacity: 0.8 }}>
              HD: {clientProfile.hdType}
            </span>
          )}
          {clientProfile.lifePath && (
            <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.9rem', opacity: 0.8 }}>
              Life Path: {clientProfile.lifePath}
            </span>
          )}
        </div>
      )}

      {/* Key Insights */}
      {s.analysis?.insights && (
        <div style={{ marginBottom: 18 }}>
          <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: '0.85rem', letterSpacing: '0.08em', color: 'var(--gold, #c9a84c)', marginBottom: 10 }}>
            ✨ Key Insights
          </h3>
          <ul style={{ margin: 0, padding: '0 0 0 18px' }}>
            {s.analysis.insights.map((insight, i) => (
              <li key={i} style={{
                fontFamily: 'Cormorant Garamond, serif',
                fontSize: '0.95rem',
                lineHeight: 1.6,
                marginBottom: 6,
              }}>
                {insight}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Action Items */}
      {s.actionItems?.length > 0 && (
        <div style={{ marginBottom: 18 }}>
          <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: '0.85rem', letterSpacing: '0.08em', color: 'var(--gold, #c9a84c)', marginBottom: 10 }}>
            ☑ Action Items
            {completedCount > 0 && (
              <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '0.8rem', marginLeft: 8, opacity: 0.7, letterSpacing: 0 }}>
                ({completedCount}/{s.actionItems.length} complete)
              </span>
            )}
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {s.actionItems.map((item, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                <span style={{
                  width: 18, height: 18, border: '1px solid var(--gold, #c9a84c)',
                  borderRadius: 3, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '0.75rem', marginTop: 2,
                  background: s.checkedItems?.[i] ? 'var(--gold, #c9a84c)' : 'transparent',
                  color: '#0f0c1e',
                }}>
                  {s.checkedItems?.[i] ? '✓' : ''}
                </span>
                <span style={{
                  fontFamily: 'Cormorant Garamond, serif',
                  fontSize: '0.95rem',
                  lineHeight: 1.5,
                  textDecoration: s.checkedItems?.[i] ? 'line-through' : 'none',
                  opacity: s.checkedItems?.[i] ? 0.5 : 1,
                }}>
                  {item}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Follow-up Questions */}
      {s.analysis?.followUpQuestions && (
        <div style={{ marginBottom: 18 }}>
          <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: '0.85rem', letterSpacing: '0.08em', color: 'var(--gold, #c9a84c)', marginBottom: 10 }}>
            ❓ Questions for Next Session
          </h3>
          <ol style={{ margin: 0, padding: '0 0 0 20px' }}>
            {s.analysis.followUpQuestions.map((q, i) => (
              <li key={i} style={{
                fontFamily: 'Cormorant Garamond, serif',
                fontSize: '0.95rem',
                lineHeight: 1.6,
                fontStyle: 'italic',
                marginBottom: 6,
              }}>
                {q}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Patterns */}
      {s.analysis?.patterns && (
        <div style={{ marginBottom: 20 }}>
          <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: '0.85rem', letterSpacing: '0.08em', color: 'var(--gold, #c9a84c)', marginBottom: 10 }}>
            🔄 Patterns Emerging
          </h3>
          <p style={{
            margin: 0,
            fontFamily: 'Cormorant Garamond, serif',
            fontSize: '0.95rem',
            lineHeight: 1.7,
            background: 'rgba(201,168,76,0.05)',
            borderLeft: '3px solid var(--gold, #c9a84c)',
            padding: '10px 14px',
            borderRadius: '0 8px 8px 0',
          }}>
            {s.analysis.patterns}
          </p>
        </div>
      )}

      {/* Action buttons */}
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <button
          onClick={handleCopy}
          style={{
            flex: 1,
            background: copied
              ? 'rgba(96,176,48,0.2)'
              : 'linear-gradient(135deg, var(--gold, #c9a84c), #e8c97a)',
            border: copied ? '1px solid #60b030' : 'none',
            borderRadius: 8,
            padding: '10px 18px',
            color: copied ? '#60b030' : '#0f0c1e',
            fontFamily: 'Cinzel, serif',
            fontSize: '0.8rem',
            letterSpacing: '0.06em',
            cursor: 'pointer',
            transition: 'all 0.3s',
          }}
        >
          {copied ? '✓ Copied!' : '📤 Send to Client'}
        </button>
        <button
          onClick={() => setShowScheduler(s => !s)}
          style={{
            flex: 1,
            background: 'var(--accent)',
            border: '1px solid var(--glass-border, rgba(201,168,76,0.3))',
            borderRadius: 8,
            padding: '10px 18px',
            color: 'var(--gold, #c9a84c)',
            fontFamily: 'Cinzel, serif',
            fontSize: '0.8rem',
            letterSpacing: '0.06em',
            cursor: 'pointer',
          }}
        >
          📅 Schedule Next Session
        </button>
      </div>

      {/* Scheduler mini-panel */}
      {showScheduler && (
        <div style={{
          marginTop: 14,
          padding: 16,
          background: 'rgba(201,168,76,0.06)',
          border: '1px solid var(--glass-border, rgba(201,168,76,0.2))',
          borderRadius: 10,
        }}>
          <p style={{ margin: '0 0 10px', fontFamily: 'Cinzel, serif', fontSize: '0.8rem', color: 'var(--gold, #c9a84c)' }}>
            Next Session
          </p>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <input
              type="date"
              style={{
                flex: 1,
                background: 'rgba(255,255,255,0.05)',
                border: '1px solid var(--glass-border, rgba(201,168,76,0.2))',
                borderRadius: 6,
                padding: '8px 10px',
                color: 'var(--text, #e8e0d5)',
                fontFamily: 'Cormorant Garamond, serif',
                fontSize: '0.9rem',
              }}
            />
            <input
              type="time"
              style={{
                flex: 1,
                background: 'rgba(255,255,255,0.05)',
                border: '1px solid var(--glass-border, rgba(201,168,76,0.2))',
                borderRadius: 6,
                padding: '8px 10px',
                color: 'var(--text, #e8e0d5)',
                fontFamily: 'Cormorant Garamond, serif',
                fontSize: '0.9rem',
              }}
            />
          </div>
          <button
            style={{
              marginTop: 10,
              width: '100%',
              background: 'rgba(201,168,76,0.15)',
              border: '1px solid var(--gold, #c9a84c)',
              borderRadius: 6,
              padding: '8px',
              color: 'var(--gold, #c9a84c)',
              fontFamily: 'Cinzel, serif',
              fontSize: '0.8rem',
              cursor: 'pointer',
            }}
          >
            Confirm & Save
          </button>
        </div>
      )}
    </div>
  )
}
